### ISSUE TITLE
Cannot download converted ProcTHOR-10K dataset

### ISSUE THREAD

**Issue by Gloria0925** [plstory/DS2D#1]
For this instruction:
You can download the converted ProcTHOR-10K dataset from [here](https://github.com/plstory/DS2D/blob/master) and put it under datasets/procthor_converted/
when I click [here](https://github.com/plstory/DS2D/blob/master) , it jumps to this tree/master webpage again. could you give a google drive or 百度网盘?

**Comment by ludolara** [comment]
Hello, we have updated the README.md with the correct [link](https://huggingface.co/datasets/ludolara/DStruct2Design). Please try downloading the dataset from there. Let us know if you encounter any further issues!
