### ISSUE TITLE
there is no [data] in “example” when I run "run_generation_rplan.py"

### ISSUE THREAD

**Issue by Gloria0925** [plstory/DS2D#2]
when I run "run_generation_rplan.py", i met an error as following:

Predicting outputs: 0%| | 0/85 [00:00<?, ?it/s] Traceback (most recent call last): File "e:\8-Floorplan\DS2D-master\run_generation_rplan.py", line 186, in <module> main(args) File "e:\8-Floorplan\DS2D-master\run_generation_rplan.py", line 175, in main predict_outputs_multiple_rplan_v1(model, tokenizer, test_dataset, exprm, num_samples=num_samples, results_dir=out_dir, start_idx=start_idx, end_idx=end_idx) File "e:\8-Floorplan\DS2D-master\run_generation_rplan.py", line 81, in predict_outputs_multiple_rplan_v1 outputs, prompt, gt = predict_output_rplan(model, tokenizer, example, model_variant, num_samples, partial_prompt) File "e:\8-Floorplan\DS2D-master\run_generation_rplan.py", line 47, in predict_output_rplan data = example['data'] KeyError: 'data'

thank you~~

**Comment by ludolara** [comment]
It looks like you were able to fix the issue yourself. That's great! If there's anything else we can improve or help with, feel free to let us know.
